namespace: sandbox
name: techtrends
service:
  type: ClusterIP
  ports:
    port: 4111
    targetPort: 3111
    protocol: TCP
image:
  repository: rehmanz/techtrends
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 2
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
containerPort: 3111
livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111
