name: Tech Trends
on: [push]
jobs:
  build_app:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Setup pipenv environment
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv --version
          pipenv install --dev
      - name: Run pre-commit checks
        run: |
          pipenv run pre-commit run --all-files
      - name: Build the app container
        run: |
          pushd app
          docker build -t app .
          popd